FROM node:21.7.1-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install --legacy-peer-deps --timeout=600000
COPY . .
RUN npm run build
FROM nginx:1.25.4-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"] 