repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        files: ^backend/.*\.py$
      - id: end-of-file-fixer
        files: ^backend/.*\.py$
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3
        args: ["--line-length=79"]
        files: ^backend/.*\.py$

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length=79"]
        files: ^backend/.*\.py$

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--max-line-length=79"]
        files: ^backend/.*\.py$
        exclude: ^backend/.*/migrations/.*$

  # Кастомный хук для финальной проверки
  - repo: local
    hooks:
      - id: final-lint-check
        name: Final lint check
        entry: python check_before_deploy.py
        language: system
        pass_filenames: false
        always_run: false
        stages: [push] 