version: '3.8'

services:
  # PostgreSQL база данных
  db:
    container_name: foodgram-dev-db
    image: postgres:13.10
    environment:
      POSTGRES_DB: foodgram_dev
      POSTGRES_USER: foodgram_user
      POSTGRES_PASSWORD: foodgram_password
    volumes:
      - pg_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Redis для кеширования и очередей
  redis:
    container_name: foodgram-dev-redis
    image: redis:7.0-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data_dev:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

  # MinIO для хранения файлов (S3-совместимое хранилище)
  minio:
    container_name: foodgram-dev-minio
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: foodgram_minio
      MINIO_ROOT_PASSWORD: foodgram_minio_password
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Web UI
    volumes:
      - minio_data_dev:/data
    restart: unless-stopped

volumes:
  pg_data_dev:
  redis_data_dev:
  minio_data_dev: 