# Generated by Django 3.2.16 on 2025-06-27 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата создания записи",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="measurement_unit",
            field=models.CharField(
                help_text="Единица измерения ингредиента",
                max_length=64,
                verbose_name="Единица измерения",
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(
                help_text="Название ингредиента",
                max_length=256,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="ingredientinrecipe",
            name="amount",
            field=models.PositiveSmallIntegerField(
                help_text="Количество ингредиента",
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Количество не может быть меньше 1"
                    ),
                    django.core.validators.MaxValueValidator(
                        10000, message="Количество не может быть больше 10000"
                    ),
                ],
                verbose_name="Количество",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveSmallIntegerField(
                help_text="Время приготовления в минутах",
                validators=[
                    django.core.validators.MinValueValidator(
                        1,
                        message="Время приготовления не может быть меньше 1 минуты",
                    ),
                    django.core.validators.MaxValueValidator(
                        10000,
                        message="Время приготовления не может быть больше 10000 минут",
                    ),
                ],
                verbose_name="Время приготовления",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="name",
            field=models.CharField(
                help_text="Название рецепта",
                max_length=256,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="shoppingcart",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата создания записи",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                help_text="Уникальное название тега",
                max_length=64,
                unique=True,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                help_text="Уникальный слаг для тега",
                max_length=64,
                unique=True,
                verbose_name="Слаг",
            ),
        ),
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
