version: '3.3'
services:

  db:
    container_name: foodgram-db
    image: postgres:13.10
    env_file: 
      - production.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    container_name: foodgram-redis
    image: redis:7.0-alpine
    env_file:
      - production.env
    command: redis-server --requirepass ${REDIS_PASSWORD}

  minio:
    container_name: foodgram-minio
    image: minio/minio
    env_file:
      - production.env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  backend:
    container_name: foodgram-backend
    build: ../backend
    env_file: 
      - production.env
    depends_on:
      - db
      - redis
      - minio

  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - static_volume:/app/result_build/
      
  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend

volumes:
  static_volume:
  postgres_data:
  minio_data:
