# Generated by Django 3.2.16 on 2025-06-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_auto_20250627_1740"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Электронная почта пользователя",
                max_length=254,
                unique=True,
                verbose_name="Электронная почта",
            ),
        ),
    ]
