name: Cleanup Production Containers

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "cleanup" to confirm'
        required: true
        default: ''

jobs:
  cleanup:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'cleanup'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cleanup Docker containers on production
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: 89.169.174.76
        username: ${{ secrets.PROD_USER }}
        key: ${{ secrets.PROD_SSH_KEY }}
        debug: true
        script: |
          echo "=== ОЧИСТКА DOCKER КОНТЕЙНЕРОВ ==="
          
          # Останавливаем все запущенные контейнеры
          echo "Останавливаем все контейнеры..."
          sudo docker stop $(sudo docker ps -q) 2>/dev/null || echo "Нет запущенных контейнеров"
          
          # Удаляем все контейнеры
          echo "Удаляем все контейнеры..."
          sudo docker rm $(sudo docker ps -aq) 2>/dev/null || echo "Нет контейнеров для удаления"
          
          # Освобождаем порты
          echo "Проверяем занятые порты..."
          sudo netstat -tlnp | grep :80 || echo "Порт 80 свободен"
          sudo netstat -tlnp | grep :443 || echo "Порт 443 свободен"
          
          # Удаляем неиспользуемые ресурсы
          echo "Удаляем неиспользуемые образы..."
          sudo docker image prune -f
          
          echo "Удаляем неиспользуемые сети..."
          sudo docker network prune -f
          
          echo "Удаляем неиспользуемые volumes..."
          sudo docker volume prune -f
          
          # Показываем текущее состояние
          echo "Текущие контейнеры:"
          sudo docker ps -a
          
          echo "Текущие образы:"
          sudo docker images
          
          echo "Доступное место на диске:"
          df -h
          
          echo "=== ОЧИСТКА ЗАВЕРШЕНА ===" 