name: Fix MinIO Images Display

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'fix'
        type: choice
        options:
          - fix
          - check
          - restart

jobs:
  fix-minio-images:
    runs-on: ubuntu-latest
    name: Fix MinIO Images Display
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Execute Fix MinIO Images Script
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            set -e
            
            echo "🔧 Исправляем проблемы с отображением изображений..."
            
            # Переходим в директорию проекта
            cd /home/yc-user/foodgram
            
            # Выбираем действие
            case "${{ github.event.inputs.action }}" in
              "fix")
                echo "🚀 Запускаем полное исправление MinIO..."
                
                # Скачиваем и запускаем скрипт исправления
                curl -s https://raw.githubusercontent.com/sergeyshmagin/foodgram/main/scripts/deploy/fix_minio_images.sh | bash
                ;;
                
              "check")
                echo "🔍 Проверяем текущее состояние MinIO..."
                
                # Проверяем статус контейнеров
                sudo docker compose -f infra/docker-compose.yml ps
                
                # Проверяем настройки MinIO
                sudo docker compose -f infra/docker-compose.yml exec -T minio mc ls minio/ || true
                
                # Проверяем доступность MinIO API
                curl -I http://89.169.174.76:9000/minio/health/live || echo "⚠️ MinIO API недоступен"
                
                # Проверяем настройки Django
                sudo docker compose -f infra/docker-compose.yml exec -T backend python manage.py shell -c "
                from django.conf import settings
                print('MEDIA_URL:', settings.MEDIA_URL)
                print('AWS_S3_ENDPOINT_URL:', settings.AWS_S3_ENDPOINT_URL)
                print('AWS_S3_CUSTOM_DOMAIN:', getattr(settings, 'AWS_S3_CUSTOM_DOMAIN', 'Not set'))
                "
                ;;
                
              "restart")
                echo "🔄 Перезапускаем сервисы..."
                
                # Перезапускаем MinIO и backend
                sudo docker compose -f infra/docker-compose.yml restart minio backend
                
                # Ждем запуска
                sleep 10
                
                # Проверяем здоровье сервисов
                sudo docker compose -f infra/docker-compose.yml ps
                ;;
            esac
            
            echo "✅ Действие '${{ github.event.inputs.action }}' выполнено!" 