name: Setup MinIO

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Причина настройки MinIO'
        required: false
        default: 'Настройка MinIO для отображения изображений'

env:
  PROD_HOST: "89.169.174.76"
  DOMAIN: "foodgram.freedynamicdns.net"

jobs:
  setup-minio:
    name: Setup MinIO on production
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup MinIO
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ env.PROD_HOST }}
        username: ${{ secrets.PROD_USER }}
        key: ${{ secrets.PROD_SSH_KEY }}
        debug: true
        script: |
          set -e
          
          echo "🔧 Настройка MinIO для отображения изображений..."
          echo "Причина: ${{ github.event.inputs.reason }}"
          
          # Переходим в рабочую директорию
          cd $HOME/foodgram
          
          # Проверяем что контейнеры запущены
          echo "📋 Проверка статуса контейнеров:"
          sudo docker compose -f infra/docker-compose.yml ps
          
          # Проверяем что MinIO работает
          if ! sudo docker compose -f infra/docker-compose.yml ps | grep minio | grep -q "Up"; then
            echo "❌ MinIO не запущен. Запускаем контейнер..."
            sudo docker compose -f infra/docker-compose.yml up -d minio
            sleep 15
          fi
          
          # Настраиваем MinIO через Docker exec
          echo "🔑 Настройка MinIO..."
          
          sudo docker compose -f infra/docker-compose.yml exec -T minio sh -c '
            # Ждём полной готовности MinIO
            echo "⏳ Ожидание готовности MinIO..."
            attempt=0
            max_attempts=30
            while [ $attempt -lt $max_attempts ]; do
              if curl -f http://localhost:9000/minio/health/live > /dev/null 2>&1; then
                echo "✅ MinIO готов"
                break
              fi
              echo "⏳ Попытка $((attempt + 1))/$max_attempts..."
              sleep 2
              attempt=$((attempt + 1))
            done
            
            if [ $attempt -eq $max_attempts ]; then
              echo "❌ MinIO не отвечает"
              exit 1
            fi
            
            # Настраиваем alias (credentials берём из переменных контейнера)
            echo "🔑 Настройка подключения..."
            mc alias set local http://localhost:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD
            
            # Создаём bucket если не существует  
            echo "📁 Создание bucket..."
            mc mb local/foodgram --ignore-existing || echo "Bucket уже существует"
            
            # Создаём папку media
            echo "📁 Создание папки media..."
            mc mb local/foodgram/media --ignore-existing || echo "Папка media уже существует"
            
            # Устанавливаем публичную политику для media
            echo "🔒 Настройка публичной политики..."
            mc anonymous set public local/foodgram/media/
            
            echo "📊 Статус bucket:"
            mc ls local/foodgram/ || echo "Bucket пуст"
            
            echo "🔒 Проверка политики:"
            mc anonymous get local/foodgram/media/ || echo "Политика не установлена"
            
            echo "✅ MinIO настроен успешно!"
          '
          
          echo "🌐 Теперь изображения должны отображаться на сайте"
          echo "🔗 Проверьте: https://${{ env.DOMAIN }}"
          
          # Проверяем что nginx корректно проксирует media
          echo "🧪 Тестируем проксирование media файлов..."
          response=$(curl -I "https://${{ env.DOMAIN }}/media/" 2>/dev/null | head -1 || echo "Тест не удался")
          echo "Ответ nginx: $response"
          
          echo "🎉 Настройка MinIO завершена!" 